//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableUsers
    {
        public string ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Fullname { get; set; }
        public string Algorithms { get; set; }
        public string Algebra { get; set; }
        public string Datamining { get; set; }
        public string WebDev { get; set; }
        public string Calculus { get; set; }
        public string OperatinsSystems { get; set; }
        public string type { get; set; }
    }
}
